./fuzz < small_input.txt > small_output.txt
./errorOne < small_errorOne.txt > errorOne_output.txt
./errorTwo < small_errorTwo.txt > errorTwo_output.txt
./errorThree < small_errorThree.txt > errorThree_output.txt
./errorFour < small_errorFour.txt > errorFour_output.txt
diff small_output.txt small_expected.txt > result_small.txt
diff errorOne_output.txt one_expected.txt > result_one.txt
diff errorTwo_output.txt two_expected.txt > result_two.txt
diff errorThree_output.txt three_expected.txt > result_three.txt
diff errorFour_output.txt four_expected.txt > result_four.txt